import { Head, Link, router, useForm } from '@inertiajs/react';
import { Link2, Link2Off, ShieldCheck } from 'lucide-react';
import AdminLayout from '@/Layouts/AdminLayout';

export default function Edit({ akun }: { akun: { name: string; username: string; email: string; google_id: string | null } }) {
  const form = useForm({ name: akun.name, email: akun.email, password_saat_ini: '', password: '', password_confirmation: '' });
  return <AdminLayout title="Profil akun" description="Kelola informasi akun dan metode masuk Anda."><Head title="Profil akun"/>
    <div className="grid max-w-4xl gap-6 lg:grid-cols-[1fr_.72fr]"><form className="spmb-panel p-6" onSubmit={(event) => { event.preventDefault(); form.put('/admin/profil'); }}><h2 className="text-lg font-bold text-ink">Informasi akun</h2><p className="mt-1 text-sm text-slate-600">Username tetap digunakan sebagai identitas login lokal.</p><div className="mt-6 grid gap-4"><label><span className="spmb-label">Nama</span><input className="spmb-input" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)}/>{form.errors.name && <p className="spmb-error">{form.errors.name}</p>}</label><label><span className="spmb-label">Username</span><input className="spmb-input bg-slate-50" value={akun.username} disabled/></label><label><span className="spmb-label">Email pemulihan</span><input className="spmb-input" type="email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)}/>{form.errors.email && <p className="spmb-error">{form.errors.email}</p>}</label></div><div className="mt-8 border-t border-slate-100 pt-6"><h3 className="font-bold text-ink">Ganti password</h3><p className="mt-1 text-sm text-slate-600">Kosongkan bila tidak ingin mengganti password.</p><div className="mt-4 grid gap-4"><label><span className="spmb-label">Password saat ini</span><input className="spmb-input" type="password" value={form.data.password_saat_ini} onChange={(event) => form.setData('password_saat_ini', event.target.value)}/>{form.errors.password_saat_ini && <p className="spmb-error">{form.errors.password_saat_ini}</p>}</label><label><span className="spmb-label">Password baru</span><input className="spmb-input" type="password" value={form.data.password} onChange={(event) => form.setData('password', event.target.value)}/></label><label><span className="spmb-label">Konfirmasi password baru</span><input className="spmb-input" type="password" value={form.data.password_confirmation} onChange={(event) => form.setData('password_confirmation', event.target.value)}/></label></div></div><button className="spmb-button-primary mt-7" disabled={form.processing}>Simpan perubahan</button></form>
    <aside className="spmb-panel h-fit p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-primary"><ShieldCheck className="h-5 w-5"/></span><h2 className="mt-5 text-lg font-bold text-ink">Login Google</h2><p className="mt-2 text-sm leading-6 text-slate-600">Google hanya dapat digunakan setelah akun lokal SPMB yang aktif menautkannya.</p>{akun.google_id ? <button type="button" onClick={() => router.delete('/admin/profil/google')} className="spmb-button-secondary mt-5 w-full"><Link2Off className="h-4 w-4"/>Lepas akun Google</button> : <a href="/auth/google" className="spmb-button-secondary mt-5 w-full"><Link2 className="h-4 w-4"/>Tautkan akun Google</a>}</aside>
    </div>
  </AdminLayout>;
}
